### PR TITLE
Rollback pre-5.1 compat changes.

### PR DESCRIPTION
**Pull request by carltongibson**
Regression in 88e60b125510a485fe5f4528e0fd3c6173bd2971.

Without adding `get_nodes_by_type()` to TemplateProxy, an error is introduced loading `extends` tags.

> AttributeError: 'TemplateProxy' object has no attribute 'get_nodes_by_type()'

Possibly:

* … caused by timing change in RenderPartialNode.
* … adding get_nodes_by_type() is correct. But tests demonstrating this would be needed.

Reverting these changes, and disabling tox run on CI to investigate at leisure.

### CODE REVIEW

File: src/template_partials/templatetags/partials.py [hunk 1]
```diff
@@ -52,11 +52,17 @@ def render(self, context):
...
+        self.origin = origin
 
     def render(self, context):
-        return self.nodelist.render(context)
+        """Render the partial content from the context"""
+        # Use the origin to get the partial content, because it's per Template,
+        # and available to the Parser.
+        # TODO: raise a better error here.
+        nodelist = self.origin.partial_contents[self.partial_name]
+        return nodelist.render(context)
```
Comment (carltongibson) [inline src/template_partials/templatetags/partials.py:65]: i.e. This change could be landed separately (if at all).
