### ISSUE TITLE
Django 5.1 compatibility

### ISSUE THREAD

**Issue by carltongibson** [carltongibson/django-template-partials#26]
Refs #25. 

> Regression in 88e60b125510a485fe5f4528e0fd3c6173bd2971.
> 
> Without adding `get_nodes_by_type()` to TemplateProxy, an error is introduced loading `extends` tags.
> 
> > AttributeError: 'TemplateProxy' object has no attribute 'get_nodes_by_type()'
> 
> Possibly:
> 
> * … caused by timing change in RenderPartialNode.
> * … adding get_nodes_by_type() is correct. But tests demonstrating this would be needed.
> 
> Reverting these changes, and disabling tox run on CI to investigate at leisure.

**Comment by carltongibson** [comment]
v24.3 added official 5.1 compat, with zero needed changes.
